server.port=${SERVER_PORT:9000}
#kafka.consumer-group=local
#kafka.server=localhost:9092
#kafka.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#kafka.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
server.servlet.context-path=/
server.error.whitelabel.enabled=false
spring.jmx.enabled=true
spring.jmx.default_domain=Kafview
spring.jackson.deserialization.fail_on_unknown_properties=false
spring.jackson.deserialization.read_unknown_enum_values_as_null:true
#management.endpoints.web.base-path=/actuator
#management.endpoints.web.exposure.include="*"
